[formatter.md]
command = "mdformat"
includes = [
  "*.md",
]

[formatter.nix]
command = "nix"
options = [
  "fmt",
]
includes = [
  "*.nix",
]

[formatter.sh]
command = "shfmt"
options = [
  "--write",
]
includes = [
  "*.sh",
  ".envrc",
]

[formatter.toml]
command = "toml-sort"
includes = [
  "*.toml",
]

[formatter.yaml]
command = "yamlfmt"
includes = [
  "*.yaml",
  "*.yml",
]

[global]
excludes = [
  "*.gitignore",
  "*.lock",
  ".editorconfig",
  "LICENSE",
]
